apiVersion: v1
kind: Service
metadata:
  name: tglobe-service
spec:
  type: NodePort
  selector:
    app: tglobe
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001 # Access via minikube_ip:30001
